#!/bin/sh

# aliases
alias v="nvim"
alias e="nvim"

alias g="git"
alias pm="yay"

alias vim="nvim"
alias trizen="yay"
alias mutt="neomutt"
alias muttorg="mutt"
alias sudo="sudo "
alias sv="systemctl"
alias sysud="yay -Syyu && pkill -RTMIN+13 i3blocks"
alias ls="ls --color=tty --group-directories-first -hNv"
alias grep="grep --color=auto"
alias diff="diff --color=auto"
alias tm="tmux attach 2> /dev/null || tmux new"
alias ll="ls -l"
alias lal="ls -al"

alias rm="rm -v"
alias mv="mv -iv"
alias cp="cp -iv"

alias yt="youtube-dl --add-metadata -i -f bestaudio/best"
alias yta="yt -x --audio-format mp3"

alias trc="transmission-remote-cli"

alias confi3="$EDITOR ~/.config/i3/config"
alias confzsh="$EDITOR ~/.config/zsh/.zshrc"
alias confi3blocks="$EDITOR ~/.config/i3blocks/config"

