#!/bin/sh

[ ! -v SSH_AUTH_SOCK ] && eval $(ssh-agent)

if [ -d $HOME/.ssh ]
then

    for key in $(find $HOME/.ssh/ -name "id_*" -not -name "*.pub")
    do
        ssh-add $key < /dev/null
    done

fi
