#!/bin/sh

eval $(ssh-agent)

export SSH_AUTH_SOCK
export SSH_AGENT_PID

    for key in $(find $HOME/.ssh/ -name "id_*" -not -name "*.pub")
    do
        ssh-add -k $key < /dev/null &>/dev/null
    done
