#!/bin/sh

API_KEY=$WEATHER_API_KEY
CITY=$WEATHER_CITY

URL="http://api.openweathermap.org/data/2.5/weather?q=${CITY}&appid=${API_KEY}&units=metric"

SYMBOL_CELSIUS="°"

ICON_SUNNY="☀️"
ICON_CLOUDY="☁️"
ICON_RAINY="🌧️"
ICON_STORM="🌬️"
ICON_SNOW="🌨️"
ICON_FOG="🌫️"

WEATHER_INFO=$(wget -qO- "${URL}")
WEATHER_MAIN=$(echo "${WEATHER_INFO}" | grep -o -e '\"main\":\"[a-Z]*\"' | awk -F ':' '{print $2}' | tr -d '"')
WEATHER_TEMP=$(echo "${WEATHER_INFO}" | grep -o -e '\"temp\":\-\?[0-9]*' | awk -F ':' '{print $2}' | tr -d '"')
if [[ "${WEATHER_MAIN}" = *Snow* ]]; then
  WEATHER_OUTPUT="${ICON_SNOW} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
elif [[ "${WEATHER_MAIN}" = *Rain* ]] || [[ "${WEATHER_MAIN}" = *Drizzle* ]]; then
  WEATHER_OUTPUT="${ICON_RAINY} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
elif [[ "${WEATHER_MAIN}" = *Thunderstorm* ]]; then
  WEATHER_OUTPUT="${ICON_STORM} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
elif [[ "${WEATHER_MAIN}" = *Cloud* ]]; then
  WEATHER_OUTPUT="${ICON_CLOUDY} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
elif [[ "${WEATHER_MAIN}" = *Clear* ]]; then
  WEATHER_OUTPUT="${ICON_SUNNY} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
elif [[ "${WEATHER_MAIN}" = *Fog* ]] || [[ "${WEATHER_MAIN}" = *Mist* ]]; then
  WEATHER_OUTPUT="${ICON_FOG} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
else
  WEATHER_OUTPUT="${WEATHER_MAIN} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
fi
#WEATHER_OUTPUT="°"
echo $WEATHER_OUTPUT | awk '{if($0!="°") print $0}'

if [[ "${WEATHER_TEMP}" -lt "${URGENT_LOWER}" ]] || [[ "${WEATHER_TEMP}" -gt "${URGENT_HIGHER}" ]]; then
  exit 33
fi
