#!/usr/bin/env sh

#dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY

[ -f "$HOME/.config/customdpi" ] && . $HOME/.config/customdpi

#[ -z $CUSTOMDPI ] && CUSTOMDPI=96

export GDK_SCALE=2
export GDK_DPI_SCALE=0.5

#dwmblocks &
mpd &
xrandr --dpi 96 &
setbg &
#xcompmgr &
picom -b --experimental-backends > /dev/null &
unclutter &
udiskie &
dunst &

#-f /usr/bin/nextcloud ] && nextcloud &&

[ -f /usr/bin/blueman-applet ] && blueman-applet &
xset s 300 0 &
xss-lock ~/.local/bin/lockscreen &
xflux -l $XFLUX_LAT -g $XFLUX_LONG > /dev/null &
