#!/usr/bin/env sh

dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY

[ -f "$HOME/.config/customdpi" ] && . $HOME/.config/customdpi

[ -z $CUSTOMDPI ] && CUSTOMDPI=192

export GDK_SCALE=2
export GDK_DPI_SCALE=0.5

#dwmblocks &
#/usr/bin/pipewire &
#/usr/bin/pipewire-pulse &
#/usr/bin/wireplumber &
mpd &
xrandr --dpi 192 &
setbg &
#xcompmgr &
picom > /dev/null &
unclutter &
udiskie &
dunst &

[ -f /usr/bin/nextcloud ] && nextcloud &

[ -f /usr/bin/blueman-applet ] && blueman-applet &

xset s 300 0 &
xss-lock ~/.local/bin/lockscreen &
xflux -l $XFLUX_LAT -g $XFLUX_LONG > /dev/null &
