#!/bin/sh

echo `trizen -Syy > /dev/null && trizen -Qu | grep -v "\[ignored\]" | wc -l | sed -e "s/^0$//g"`

case $BLOCK_BUTTON in
  1)
    "$TERMINAL" -e trizen -Syyu && pkill -RTMIN+13 i3block
;;
esac
